### ISSUE TITLE
Asia/Ho_Chi_Minh is missed

### ISSUE THREAD

**Issue by shinji1985** [sanohin/google-timezones-json#1]
Hi. thank you for your great work.
I'm using this json data in my app.
By the way, I found Asia/Ho_Chi_Minh is missed from the list.
Usually Asia/Saigon is used for my calendar timezone. but when i set 2 timezone for my calendar, my google calendar will return Asia/Ho_Chi_Minh instead of Asia/Saigon.
So its better to add Asia/Ho_Chi_Minh also in the timezone list.

**Comment by sanohin** [comment]
Hi, thank you
You can install 1.0.2, I added Ho Chi Minh timezone.
