### ISSUE TITLE
Please change "Kiev" to "Kyiv" to counter Imperialism, support Ukrainians' right to own culture and self determination

### ISSUE THREAD

**Issue by maxtkacz** [sanohin/google-timezones-json#4]
the n8n app uses google-timezones-json and we had a few Ukrainian users report that "Kyiv" is misspelled as "Kiev". I do mean misspelled, "Kiev" is the transliteration of Russian to English, whereas "Kyiv" is transliteration of Ukrainian. 

This is a very important nuance for Ukrainians, especially as they fight to defend their own freedom from Russian Imperialism. It's this same Russian Imperialism that has caused the west to traditionally opt to use "Kiev" instead of "Kyiv".

I ask that you please make this small change, as most folks who will reference this package will not know of this issue (I don't expect everyone to be as educated on Ukrainian issues as Ukrainians) but I promise you it's meaningful for Ukrainians when we see this. 

To pre-emptively counter typical arguments against this change(sorry, you get used to doing that as a Ukrainian online), Ukrainian is the official language of Ukraine (just like in most European countries - German is the official language of Germany). Thus, it only makes sense that the transliterated english word for our capital is derived from Ukrainian.

Thanks in advance for your consideration. I'd submit the PR myself, but I'm not really good at all that; am a UX designer :) 

🇺🇦

**Comment by sanohin** [comment]
@maxtkacz  @Joffcom thank you for raising and fixing this! I completely forgot about this package and repository 🙂
It is released in `v1.1.0`
